{{- if .Values.ingress.enabled -}}
{{- $fullName := include "sonarr.fullname" . -}}
{{- $hostName := .Values.ingress.host -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ include "sonarr.name" . }}
    helm.sh/chart: {{ include "sonarr.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ $hostName | quote }}
{{- end }}
  rules:
    - host: {{ $hostName | quote }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
{{- end }}
