# Default values for radarr

timeZone: Europe/Zurich

uid: "10001"
gid: "10001"

persistence:
  enabled: true
  config:
    size: 1Gi
    storageClass: ""
    accessModes: ["ReadWriteOnce"]
    selector:
    # matchLabels:
    #   some: label
  volumeClaimNamePlex: plex-data
  subPathAddons: addons/
  subPathPlex: Movies/

image:
  repository: docker.io/linuxserver/radarr
  tag: 0.2.0.1343-ls15
  pullPolicy: IfNotPresent

gatekeeper:
  repository: quay.io/keycloak/keycloak-gatekeeper
  tag: 9.0.2
  pullPolicy: IfNotPresent

  discoveryUrl: https://sso.srueg.ch/auth/realms/lab
  clientId: radarr
  existingSecret: radarr-gatekeeper

nameOverride: ""
fullnameOverride: ""

ingress:
  enabled: false
  annotations:
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    # certmanager.k8s.io/acme-http01-edit-in-place: "true"
  host: # chart-example.local
  tls: true

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
