# Default values for nzbget

timeZone: Europe/Zurich

uid: "10001"
gid: "10001"
enableHealthChecks: true

persistence:
  enabled: true
  config:
    size: 1Gi
    storageClass: ""
    accessModes: ["ReadWriteOnce"]
    selector:
    #  matchLabels:
    #    some: label
  downloads:
    size: 50Gi
    storageClass: ""
    accessModes: ["ReadWriteOnce"]
    selector:
    # matchLabels:
    #   some: label

image:
  repository: docker.io/linuxserver/nzbget
  tag: v20.0-ls5
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations:
    # kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/acme-http01-edit-in-place: "true"
  host: # chart-example.local
  tls: true

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
