apiVersion: v1
kind: Service
metadata:
  name: {{ include "transmission.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "transmission.name" . }}
    helm.sh/chart: {{ include "transmission.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app.kubernetes.io/name: {{ include "transmission.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
